### PR TITLE
Convert enums to scoped enums

### PR DESCRIPTION
**Pull request by mariusmuja**
This converts enums to scoped enums (`enum class`) for better type safety. It also eliminates some code by adding an `ENUM()` macro that generates the enum together with an `EnumName_to_string(enum)` functios and a safe from int conversion `to_EnumName(int, default)`.

Also adds `this->` to member method calls as per the esphome coding conventions.

### CODE REVIEW

**Comment by bdraco** [comment]
Side note. It look like memory allocation / collection is a bit more up and down after #27

I installed it around 10pm last night

Screenshot 2023-07-03 at 8 09 49 AM

**Comment by mariusmuja** [comment]
Hmm, that's very strange, I don't see anything in #27 that could cause that. The only thing memory related in #27 is the move of `txRollingCode` and `txRollingCode` from class members to the stack & static variable, but that should not impact the heap.

Also, for me the memory profile has always looked like it looks for you now. Are you sure that #27 was the only change that happened (no esphome updates)?. I guess you could try reverting to before #27 and see if changes the memory allocation to how it was before.

**Comment by bdraco** [comment]
No esphome update happened. I'll try reverting #27

**Comment by bdraco** [comment]
I just looked at the graph again which is running this PR and its back to how it was before

Screenshot 2023-07-03 at 11 45 07 AM

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
> Hmm, that's very strange, I don't see anything in #27 that could cause that. The only thing memory related in #27 is the move of `txRollingCode` and `txRollingCode` from class members to the stack & static variable, but that should not impact the heap.

Agreed. I'm not sure whats going on there. I'll keep watching it

**Pull request merged**
