### PR TITLE
Collision detection on transmit

### PR DESCRIPTION
**Pull request by mariusmuja**
Currently we're "blindly" transmitting without checking if there's another device transmitting at the same time. This adds a check to ensure the line is idle before transmitting a packet.

### CODE REVIEW

**Comment by mariusmuja** [comment]
A way to see this "in action" is by pressing the `Query status` button in quick succession to trigger collisions between `GET_STATUS` commands and `STATUS` replies. Without the collision detection:

```
[23:53:56][D][button:010]: 'Query status' Pressed.
[23:53:56][D][number:012]: 'Rolling code counter': Sending state 9532.000000
[23:53:56][D][ratgdo:097]: [55644] received mine: rolling=000253b fixed=0000000539 data=00000080
[23:53:56][D][button:010]: 'Query status' Pressed.
[23:53:56][D][number:012]: 'Rolling code counter': Sending state 9533.000000
[23:53:56][D][ratgdo:100]: [55768] received rolling=0000000 fixed=0000000000 data=00000000
[23:53:56][D][ratgdo:107]: cmd=000 (UNKNOWN) byte2=00 byte1=00 nibble=0
[23:53:56][D][ratgdo:100]: [55855] received rolling=0000000 fixed=0000000000 data=00000000
[23:53:56][D][ratgdo:107]: cmd=000 (UNKNOWN) byte2=00 byte1=00 nibble=0
[23:53:56][D][button:010]: 'Query status' Pressed.
```
where `cmd=000` are corrupted packets due to transmit collisions while the opener replies.

With the collision detection, no more `cmd=000` and we can see that collisions are detected and avoided:
```
[00:03:48][D][ratgdo:112]: cmd=081 (STATUS) byte2=40 byte1=60 nibble=2
[00:03:48][D][ratgdo:178]: Status: door=CLOSED light=OFF lock=UNLOCKED
[00:03:48][D][button:010]: 'Query status' Pressed.
[00:03:48][D][number:012]: 'Rolling code counter': Sending state 9570.000000
[00:03:48][D][ratgdo:102]: [151285] received mine: rolling=0002561 fixed=0000000539 data=00000080
[00:03:49][D][button:010]: 'Query status' Pressed.
[00:03:49][D][ratgdo:404]: Collision detected, waiting to send packet
[00:03:49][D][number:012]: 'Rolling code counter': Sending state 9571.000000
[00:03:49][D][ratgdo:105]: [151412] received rolling=0013fb4 fixed=805c50c2c2 data=40600281
[00:03:49][D][ratgdo:112]: cmd=081 (STATUS) byte2=40 byte1=60 nibble=2
```

**Comment by bdraco** [comment]
LGTM

Testing shortly

**Comment by bdraco** [comment]
Seems to work fine.

I noticed that its saving prefs to flash during opening/closing, but I think thats from the previous PR

```
[13:48:45][D][cover:170]: 'Door' - Publishing:
[13:48:45][D][cover:173]:   Position: 99%
[13:48:45][D][cover:186]:   Current Operation: OPENING
[13:48:46][D][ratgdo:240]: Set opening duration: 12.1s
[13:48:46][D][ratgdo:574]: Cancelling position callbacks
[13:48:46][D][ratgdo:178]: Status: door=OPEN light=ON lock=UNLOCKED
[13:48:46][D][cover:170]: 'Door' - Publishing:
[13:48:46][D][cover:173]:   Position: 100%
[13:48:46][D][cover:186]:   Current Operation: IDLE
[13:48:46][D][switch:012]: 'Status door' Turning ON.
[13:48:46][D][switch:055]: 'Status door': Sending state ON
[13:48:46][D][binary_sensor:036]: 'Motor': Sending state OFF
[13:48:48][D][esp8266.preferences:238]: Saving preferences to flash...
[13:48:49][D][cover:076]: 'Door' - Setting
[13:48:49][D][cover:084]:   Position: 0%
[13:48:49][D][ratgdo:410]: Collision detected, waiting to send packet
[13:48:49][D][ratgdo:410]: Collision detected, waiting to send packet
[13:48:49][D][number:012]: 'Rolling code counter': Sending state 386.000000
[13:48:50][D][ratgdo:178]: Status: door=CLOSING light=ON lock=UNLOCKED
[13:48:50][D][cover:170]: 'Door' - Publishing:
[13:48:50][D][cover:173]:   Position: 97%
[13:48:50][D][cover:186]:   Current Operation: CLOSING
[13:48:50][D][ratgdo:196]: Motor: state=ON
[13:48:50][D][binary_sensor:036]: 'Motor': Sending state ON
[13:48:50][D][cover:170]: 'Door' - Publishing:
[13:48:50][D][cover:173]:   Position: 94%
[13:48:50][D][cover:186]:   Current Operation: CLOSING
[13:48:51][D][cover:170]: 'Door' - Publishing:
[13:48:51][D][cover:173]:   Position: 91%
[13:48:51][D][cover:186]:   Current Operation: CLOSING
[13:48:51][D][cover:170]: 'Door' - Publishing:
[13:48:51][D][cover:173]:   Position: 88%
[13:48:51][D][cover:186]:   Current Operation: CLOSING
[13:48:52][D][cover:170]: 'Door' - Publishing:
[13:48:52][D][cover:173]:   Position: 85%
[13:48:52][D][cover:186]:   Current Operation: CLOSING
[13:48:52][D][cover:170]: 'Door' - Publishing:
[13:48:52][D][cover:173]:   Position: 81%
[13:48:52][D][cover:186]:   Current Operation: CLOSING
[13:48:53][D][cover:170]: 'Door' - Publishing:
[13:48:53][D][cover:173]:   Position: 78%
[13:48:53][D][cover:186]:   Current Operation: CLOSING
[13:48:53][D][esp8266.preferences:238]: Saving preferences to flash...
[13:48:53][D][cover:170]: 'Door' - Publishing:
[13:48:53][D][cover:173]:   Position: 75%
[13:48:53][D][cover:186]:   Current Operation: CLOSING
[13:48:54][D][cover:170]: 'Door' - Publishing:
[13:48:54][D][cover:173]:   Position: 72%
[13:48:54][D][cover:186]:   Current Operation: CLOSING
[13:48:54][D][cover:170]: 'Door' - Publishing:
[13:48:54][D][cover:173]:   Position: 69%
[13:48:54][D][cover:186]:   Current Operation: CLOSING
[13:48:55][D][cover:170]: 'Door' - Publishing:
[13:48:55][D][cover:173]:   Position: 66%
[13:48:55][D][cover:186]:   Current Operation: CLOSING
[13:48:55][D][cover:170]: 'Door' - Publishing:
[13:48:55][D][cover:173]:   Position: 63%
[13:48:55][D][cover:186]:   Current Operation: CLOSING
[13:48:56][D][cover:170]: 'Door' - Publishing:
[13:48:56][D][cover:173]:   Position: 60%
[13:48:56][D][cover:186]:   Current Operation: CLOSING
[13:48:56][D][cover:170]: 'Door' - Publishing:
[13:48:56][D][cover:173]:   Position: 57%
[13:48:56][D][cover:186]:   Current Operation: CLOSING
[13:48:56][D][ratgdo:196]: Motor: state=ON
[13:48:57][D][cover:170]: 'Door' - Publishing:
[13:48:57][D][cover:173]:   Position: 54%
[13:48:57][D][cover:186]:   Current Operation: CLOSING
[13:48:57][D][cover:170]: 'Door' - Publishing:
[13:48:57][D][cover:173]:   Position: 51%
[13:48:57][D][cover:186]:   Current Operation: CLOSING
[13:48:58][D][cover:170]: 'Door' - Publishing:
[13:48:58][D][cover:173]:   Position: 48%
[13:48:58][D][cover:186]:   Current Operation: CLOSING
[13:48:58][D][esp8266.preferences:238]: Saving preferences to flash...
[13:48:58][D][cover:170]: 'Door' - Publishing:
[13:48:58][D][cover:173]:   Position: 44%
[13:48:58][D][cover:186]:   Current Operation: CLOSING
[13:48:59][D][cover:170]: 'Door' - Publishing:
[13:48:59][D][cover:173]:   Position: 41%
[13:48:59][D][cover:186]:   Current Operation: CLOSING
[13:48:59][D][cover:170]: 'Door' - Publishing:
[13:48:59][D][cover:173]:   Position: 38%
[13:48:59][D][cover:186]:   Current Operation: CLOSING
[13:49:00][D][cover:170]: 'Door' - Publishing:
[13:49:00][D][cover:173]:   Position: 35%
[13:49:00][D][cover:186]:   Current Operation: CLOSING
[13:49:00][D][cover:170]: 'Door' - Publishing:
[13:49:00][D][cover:173]:   Position: 32%
[13:49:00][D][cover:186]:   Current Operation: CLOSING
[13:49:01][D][cover:170]: 'Door' - Publishing:
[13:49:01][D][cover:173]:   Position: 29%
[13:49:01][D][cover:186]:   Current Operation: CLOSING
[13:49:01][D][cover:170]: 'Door' - Publishing:
[13:49:01][D][cover:173]:   Position: 26%
[13:49:01][D][cover:186]:   Current Operation: CLOSING
[13:49:01][D][ratgdo:196]: Motor: state=ON
[13:49:02][D][cover:170]: 'Door' - Publishing:
[13:49:02][D][cover:173]:   Position: 23%
[13:49:02][D][cover:186]:   Current Operation: CLOSING
[13:49:02][D][cover:170]: 'Door' - Publishing:
[13:49:02][D][cover:173]:   Position: 20%
[13:49:02][D][cover:186]:   Current Operation: CLOSING
[13:49:03][D][cover:170]: 'Door' - Publishing:
[13:49:03][D][cover:173]:   Position: 17%
[13:49:03][D][cover:186]:   Current Operation: CLOSING
[13:49:03][D][esp8266.preferences:238]: Saving preferences to flash...
[13:49:03][D][cover:170]: 'Door' - Publishing:
[13:49:03][D][cover:173]:   Position: 14%
[13:49:03][D][cover:186]:   Current Operation: CLOSING
[13:49:04][D][cover:170]: 'Door' - Publishing:
[13:49:04][D][cover:173]:   Position: 10%
[13:49:04][D][cover:186]:   Current Operation: CLOSING
[13:49:04][D][cover:170]: 'Door' - Publishing:
[13:49:04][D][cover:173]:   Position: 7%
[13:49:04][D][cover:186]:   Current Operation: CLOSING
[13:49:05][D][ratgdo:196]: Motor: state=ON
[13:49:05][D][cover:170]: 'Door' - Publishing:
[13:49:05][D][cover:173]:   Position: 4%
[13:49:05][D][cover:186]:   Current Operation: CLOSING
[13:49:05][D][cover:170]: 'Door' - Publishing:
[13:49:05][D][cover:173]:   Position: 1%
[13:49:05][D][cover:186]:   Current Operation: CLOSING
[13:49:06][D][ratgdo:250]: Set closing duration: 16.3s
[13:49:06][D][ratgdo:574]: Cancelling position callbacks
[13:49:06][D][ratgdo:178]: Status: door=CLOSED light=ON lock=UNLOCKED
[13:49:06][D][number:012]: 'Closing duration': Sending state 16.299999
[13:49:06][D][cover:170]: 'Door' - Publishing:
[13:49:06][D][cover:173]:   Position: 0%
[13:49:06][D][cover:186]:   Current Operation: IDLE
[13:49:06][D][switch:016]: 'Status door' Turning OFF.
[13:49:06][D][switch:055]: 'Status door': Sending state OFF
[13:49:06][D][binary_sensor:036]: 'Motor': Sending state OFF
[13:49:06][D][number:012]: 'Rolling code counter': Sending state 387.000000
[13:49:06][D][ratgdo:205]: Openings: 5412
[13:49:06][D][sensor:093]: 'Openings': Sending state 5412.00000 openings with 0 decimals of accuracy
[13:49:08][D][esp8266.preferences:238]: Saving preferences to flash...
```

**Comment by mariusmuja** [comment]
> I noticed that its saving prefs to flash during opening/closing, but I think thats from the previous PR

Yes, it's from the save/restore of door position. It writes to flash every 5s if something changed and during opening/closing the door position changes. 

I think the flash write interval can probably be increased, on start we increment  the rolling code by 10 and then try to sync 10 times, so we can fail to write 19 codes and still be ok.

**Review by bdraco — COMMENTED** [review]
Testing went as expected 👍

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks @mariusmuja

**Comment by bdraco** [comment]
Looks like the build failed

https://github.com/ESPHome-RATGDO/esphome-ratgdo/actions/runs/5491654492/jobs/10008401969

**Comment by mariusmuja** [comment]
Yes, it seems that `micros64()` is not available on esp32. I pushed a fix.

**Pull request merged**
