### PR TITLE
Better sync

### PR DESCRIPTION
**Pull request by mariusmuja**
No need to send multiple GET_STATUS commands to increment rolling counter, we can just increment the rolling counter, the opener will accept forward jumps in the counter.

Improved the get status and openings by retrying to request the updates with backoff. My opener seems to stop sending replies for the same command sent multiple times in quick succession until some amount of time has passed.

### CODE REVIEW

**Comment by bdraco** [comment]
Looks good. Will test when I get back home in a few hours

**Comment by bdraco** [comment]
I think it will accept up to 1000 jumps so we could make it even safer against unhandled resets by always bumping by 10

**Comment by mariusmuja** [comment]
Sounds good to me.

**Review by bdraco — APPROVED** [review]
Manual testing is good 👍 

Thanks @mariusmuja

**Pull request merged**
